In [18]:
def square(x):
    return x**2
for N in range(1,4):
    print(N,"의 제곱은",square(N))

1 의 제곱은 1
2 의 제곱은 4
3 의 제곱은 9


In [19]:
import math
math.sin(2)

0.9092974268256817

In [5]:
import numpy
numpy.__version__

'1.13.3'

In [6]:
result = 0
for i in range(100):
    result += i

In [7]:
print(result)

4950


In [17]:
%cd data
print(address)

[Errno 2] No such file or directory: 'data'
/home/changawan/data/data
['/home/changawan/data/python']


In [3]:
import numpy as np
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [1]:
import array
L=list(range(10))
A=array.array('i',L) # i는 integer 타입코드
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#numpy array의 명시적 다차원
#리스트를 중첩해서 다차원 배열을 만든다???
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.ones((3,5),dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [7]:
np.full((3,5),3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [9]:
#수열로 배열 채우기
#0에서 시작 20까지 채움
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.linspace(0,1,5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [11]:
np.linspace(0,0.14,10)

array([ 0.        ,  0.01555556,  0.03111111,  0.04666667,  0.06222222,
        0.07777778,  0.09333333,  0.10888889,  0.12444444,  0.14      ])

In [12]:
np.random.random((3,3))

array([[ 0.27883603,  0.08553516,  0.53876469],
       [ 0.27733769,  0.94053098,  0.51456956],
       [ 0.22276246,  0.11915929,  0.13698331]])

In [14]:
# normal distribution random number (average = 0, standard deviation = 1) 3x3 matrix
np.random.normal(0,1,(3,3))

array([[ 0.00825041,  0.83477136, -0.50882425],
       [-0.47116973,  0.38853694,  0.97143974],
       [-0.69188787,  0.89130211,  0.0638276 ]])

In [15]:
#[0,10]구간 임의의 정수로 채운 3x3 배열 만들기
np.random.randint(0,10,(3,3))



array([[3, 2, 3],
       [1, 0, 2],
       [8, 6, 8]])

In [16]:
#3x3 단위행렬 만들기
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [ ]:
#기본 배열 조작
#배열 속성 지정 : 배열의 크기, 모양, 메모리 소비량, 데이터 타입 결정
# 배열 인덱싱 : 개별 배열 요솟값을 가져오고 설정한다.
#배열 슬라이싱 : 큰 배열 내에 있는 작은 하위 배열을 가져오고 설정한다.
#배열 재구조화 : 해당 배열의 형상을 변경한다.
#배열 결합 및 분할 : 여러 배열을 하나로 결합하고 하나의 배열을 여러개로 분할한다.

In [66]:
import numpy as np
np.random.seed(0) #재현 가능성을 위한 시드값
x1 = np.random.randint(10,size=6) #1차원 배열
x2 = np.random.randint(10,size=(3,4)) #2차원 배열
x3 = np.random.randint(10,size=(3,4,5)) #3차원 배열
x4 = np.random.randint(10,size=(3,4,5,6)) 

In [20]:
x1

array([5, 0, 3, 3, 7, 9])

In [21]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [22]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [24]:
x4

array([[[[4, 3, 4, 4, 8, 4],
         [3, 7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5, 0],
         [1, 2, 4, 2, 0, 3],
         [2, 0, 7, 5, 9, 0]],

        [[2, 7, 2, 9, 2, 3],
         [3, 2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8, 2],
         [3, 0, 0, 6, 0, 6],
         [3, 3, 8, 8, 8, 2]],

        [[3, 2, 0, 8, 8, 3],
         [8, 2, 8, 4, 3, 0],
         [4, 3, 6, 9, 8, 0],
         [8, 5, 9, 0, 9, 6],
         [5, 3, 1, 8, 0, 4]],

        [[9, 6, 5, 7, 8, 8],
         [9, 2, 8, 6, 6, 9],
         [1, 6, 8, 8, 3, 2],
         [3, 6, 3, 6, 5, 7],
         [0, 8, 4, 6, 5, 8]]],


       [[[2, 3, 9, 7, 5, 3],
         [4, 5, 3, 3, 7, 9],
         [9, 9, 7, 3, 2, 3],
         [9, 7, 7, 5, 1, 2],
         [2, 8, 1, 5, 8, 4]],

        [[0, 2, 5, 5, 0, 8],
         [1, 1, 0, 3, 8, 8],
         [4, 4, 0, 9, 3, 7],
         [3, 2, 1, 1, 2, 1],
         [4, 2, 5, 5, 5, 2]],

        [[5, 7, 7, 6, 1, 6],
         [7, 2, 3, 1, 9, 5],
         [9, 9, 2, 0, 9, 1],
         [9, 0, 6, 0, 4, 8],


In [30]:
#각 배열은 속성으로 차원의 개수(ndim), 각 차원의 크기(shape) 전체 배열의 크기(size) 세가지를 가지고 있다.
print(x4.ndim,x4.shape,x4.size,x4.dtype)
print(x4.itemsize,x4.nbytes)

4 (3, 4, 5, 6) 360 int64
8 2880


In [45]:
x4[0,0,0,0]

1

In [57]:
#하위 배열에 접근하기 : x[start:stop:step]
#정해지지 않으면 기본으로 start = 0, stop = ndim, step=1로 설정된다.

#1차원 하위배열
np.random.seed(10)
x= np.random.randint(10,size=10)
x[5:]

array([0, 1, 8, 9, 0])

In [8]:
x2[:2,:3]

array([[3, 5, 2],
       [7, 6, 8]])

In [16]:
print(x2)
x2[::-1,::-1]

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [22]:
print(x2[:,0])

[3 7 1]


In [23]:
 x2_sub_copy = x2[:2,:2].copy()
#copy()를 쓰면 사본으로 만든다.

In [24]:
x2_sub_copy

array([[3, 5],
       [7, 6]])

In [32]:
np.zeros(10,dtype=float)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [35]:
#배열 연결
# 배열 연결에는 np.concatenate, np.vstack, np.hstack 루틴을 이용해 두 배열을 결합하거나 연결한다.
# np.concatenate는 튜플이나 배열의 리스트를 첫번째 인수로 취한다.
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])
#3개도 가능하다.
z = np.array([99,99,99])
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [42]:
# 2 차원 배열의 np.concatenate
grid = np.array([[1,2,3],[4,5,6]])
print(grid)
np.concatenate([grid,grid])
#두번째 축을 따라 연결
np.concatenate([grid,grid],axis = 1)

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [58]:
#2차원 배열의 np.concatenate 2
print(np.concatenate([x3,x3],axis = 0))
print('###############')
print(np.concatenate([x3,x3]))
# 모르겠는걸?

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]

 [[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
###############
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]

 [[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [63]:
#혼합된 차원을 배열을 작업할땐 np.vstack(수직스택, vertical stack)과 np.hstack(수평스택) 함수를 사용하는게 더 명확하다.
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x,[3,5]) #3,5 인덱스로 잘라준다. N개의 분할점은  N+1의 하위 배열을 만든다.
print(x1,x2,x3)



[1 2 3] [99 99] [3 2 1]


array([3, 2, 1])

In [86]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [97]:
upper, lower = np.vsplit(grid,[2])
left, right = np.hsplit(grid,[2])

In [89]:
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [98]:
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [101]:
#numpy 배열 연산 : 유니버셜 함수
# numpy 배열 연산은 vectorized 연산을 하는데, 유니버셜 함수를 통해 구현된다. 
import numpy as np
np.random.seed(0)
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output
values = np.random.randint(1,10,size=5)
compute_reciprocals(values)
    

array([ 0.16666667,  1.        ,  0.25      ,  0.25      ,  0.125     ])

In [102]:
big_array = np.random.randint(1,100,size=1000000)
%timeit compute_reciprocals(big_array)
'''
병목이ㅣ 연산 자체에 있는게 아니라 CPython이 루프의 사이클마다 수행해야하는 타입확인과 함수 디스패치에서 발생한다.
역수가 계산될때마다 파이썬은 먼저 객체의 타입을 확인하고 해당 타입에 맞게 사용할 적절한 함수를 동적으로 검색한다.
컴파일된 코드로 작업했다면 코드를 실행하기 전에 타입을 알았을 것이고, 결과값은 좀 더 효율적으로 계산됐을것이다.

UFuncs
numpy는 정적 타입을 가진 컴파일된 루틴에 편리한 인터페이스를 제공한다?
이를 벡터화 연산이라고 한다.
백터화 연산은 간단히 배열에 연산을 수행해 각 요소에 적용한다.
벡터화 방식은 루프를 컴파일된 계층으로 계산해서 훨씬 빠르게 실행되도록 설계되었다.
'''

3.02 s ± 19.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [103]:
print(compute_reciprocals(values))
print(1.0/values)

[ 0.16666667  1.          0.25        0.25        0.125     ]
[ 0.16666667  1.          0.25        0.25        0.125     ]


In [104]:
%timeit (1.0/big_array)
#numpy에서 벡터화 연산은 배열의 값에 반복된 연산을 빠르게 수행하는 것을 주목적으로 하는 ufuncs를 통해 구현된다.
#ufuncs는 굉장히 유연해서 스칼라와 배열 사이의 연산, 두 배열 간의 연산도 가능하다.

2.49 ms ± 18.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [112]:
%timeit np.arange(5)/np.arange(1,6)

2.6 µs ± 18.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [122]:
#벡터화 연산은 루프를 이용한 연산보다 대부분 더 효율적이며 배열이 커질 수록 그 차이가 확연하다.
#기본적인 사칙연산 + 제곱, 나머지 연산자 다 된다.
x = np.arange(1,4)
x*(-1)

array([-1, -2, -3])

In [127]:
#절댓값 함수 사용가능 , 허수에도 적용된다.
x = np.arange(-2,2)
np.absolute(x)

array([2, 1, 0, 1])

In [129]:
#삼각함수 적용 가능
theta = np.linspace(0,np.pi,3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[ 0.          1.57079633  3.14159265]
[  0.00000000e+00   1.00000000e+00   1.22464680e-16]
[  1.00000000e+00   6.12323400e-17  -1.00000000e+00]
[  0.00000000e+00   1.63312394e+16  -1.22464680e-16]


In [132]:
x = [-1,0,1]
print(np.arcsin(x)/np.pi)
print(np.arccos(x)/np.pi)
print(np.arctan(x)/np.pi)


[-0.5  0.   0.5]
[ 1.   0.5  0. ]
[-0.25  0.    0.25]


In [133]:
### 지수와 로그
x=[1,2,3]
print(np.exp(x))
print(np.exp2(x))
print(np.power(3,x))


[  2.71828183   7.3890561   20.08553692]
[ 2.  4.  8.]
[ 3  9 27]


In [138]:
#자연상수가 default
x = [1,np.e,4,10]
print(np.log(x))
print(np.log2(x))
print(np.log10(x))

[ 0.          1.          1.38629436  2.30258509]
[ 0.          1.44269504  2.          3.32192809]
[ 0.          0.43429448  0.60205999  1.        ]


In [142]:
#numpy에는 쌍곡선 삼각함수, 비트연산, 비교연산자, 라디안을 각도로 변환, 반올림과 나머지 등을 나타낼 수 있다.
#전문적이고 보기 드문 ufunc은 scipy.special에 있다.
from scipy import special
#감마 함수(일반화된 계승)과 관련 함수
x = [1,5,10]
print('gamma(x) = ', special.gamma(x))
print('ln|gamma(x)| = ', special.gammaln(x))
print(special.beta(x,2))

gamma(x) =  [  1.00000000e+00   2.40000000e+01   3.62880000e+05]
ln|gamma(x)| =  [  0.           3.17805383  12.80182748]
[ 0.5         0.03333333  0.00909091]


In [ ]:
#고급 ufunc 기능 
#1. 출력지정 : 대규모 연산인 경우 연산결과를 저장할 배열을 지정하는게 유옹할 때가 있다.
#임시 배열을 생성하지 않고 지정한 배열을 이용해 원하는 메모리 위치에 직접 연산 결과를 쓸 수 있다.



In [2]:
import numpy as np 
L = np.random.random(100)
sum(L)

47.57967771356364

In [3]:
np.sum(L)

52.724419728306856

In [5]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

#np.sum의 경우 다중 배열 차원ㅇ르 인지한다.



71 ms ± 1.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
360 µs ± 6.23 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
0.999999832617
7.29270333122e-07


In [7]:
print(max(big_array))
print(min(big_array))
#다차원 집계
M = np.random.random((3,4))
print(M)

0.999999832617
7.29270333122e-07
[[ 0.54654282  0.80880016  0.25039479  0.16412348]
 [ 0.65590174  0.51626997  0.64169226  0.87245776]
 [ 0.7901843   0.7955313   0.36710771  0.20779334]]


In [8]:
M.sum()

6.6167996274734797

In [9]:
#각 열의 최솟값을 출력할 수 있다.
M.min(axis=0)

array([ 0.54654282,  0.51626997,  0.25039479,  0.16412348])

In [10]:
!head /home/changawan/data/data/president_heights.csv

order,name,height(cm)
1,George Washington,189
2,John Adams,170
3,Thomas Jefferson,189
4,James Madison,163
5,James Monroe,183
6,John Quincy Adams,171
7,Andrew Jackson,185
8,Martin Van Buren,168
9,William Henry Harrison,173


In [4]:
import pandas as pd
data = pd.read_csv('/home/changawan/data/data/president_heights.csv')
heights = np.array(data['height(cm)']) #heights(cm)이라는 컬럼을 뽑아온다.
print(heights)

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]


In [5]:
print("Mean height  : ", heights.mean())#평균 키
print("Standard deviation : ", heights.std())#표준편차
print("Minimun heights : ", heights.min())
print("Maximun heights : ",heights.max())

Mean height  :  179.738095238
Standard deviation :  6.93184344275
Minimun heights :  163
Maximun heights :  193


In [7]:
print("25th percentile: ",np.percentile(heights,25))
print("median: ", np.median(heights))
print("75th percentile: ",np.median(heights))

25th percentile:  174.25
median:  182.0
75th percentile:  182.0


In [2]:
import numpy as np

In [9]:
#배열 연산 : 브로드캐스팅
'''
느린 파이썬의 루프를 제거하기위해 벡터화 했다.
numpy는 브로드캐스팅 기능이 있다.
다른크기의 배열에 이행 유니버셜 함수(덧셈,뺄셈) 을 적용하기 위한 규칙의 집합
'''
#브로드 캐스팅 소개 : 같은 크기의 배열에서 이항연산은 배열의 요소단위로 수행된다.
a=np.array([0,1,2]) #리스트를 어레이처리한다.
b=np.array([5,5,5])
a+b
#array([5, 6, 7])
'''
브로드캐스팅을 사용하면 이러한 유형의 이항 연산을 다른 크기의 배열에서 수행 할 ㅅ 윘다.
배열에 스칼라(0차원의 배열)를 쉽게 더할 수 있다.
'''
a+5
#array([5, 6, 7])


array([5, 6, 7])

쉽게 생각해서 5,5,5 배열을 더한다고 생각하면 된다.
브로드 캐스팅의 장점 : 값 복제가 실제로 발생하지 않는다.
높은 차원의 배열로 확장해보자.

In [12]:
M = np.ones((3,3))
M

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [13]:
M+a
'''
array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])
결과를 해석해보면 a는 M의 형상에 맞추기 위해 두번째 차원까지 확장 또는 브로드캐스팅된다.
두 배열 모두 브로드캐스팅해야하는 경우 복잡해진다.
'''


array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

In [26]:
a = np.arange(3)
b = np.arange(3)[:,np.newaxis]

'''
a
array([0, 1, 2])
b
array([[0],
       [1],
       [2]])
a+b
array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])
위 결과는 a와  b 모두 브로드캐스팅되었다.
    
'''
b+a

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

브로드캐스팅의 규칙을 알아보자
1. 두 배열의 차원수가 다르면 더 적은수의 차원을 가진 배열 형상의 앞쪽(왼쪽)을 1로 채운다.
2. 두 배열의 형상이 어떤 차원에서도 일치하지 않는다면 해당 차원의 형상이 1인 배열이 다른 형상과 일치하도록 늘어난다.
3. 임의의 차원에서 크기가 일치하지 않고 1도 아니라면 오류가 발생한다.

In [56]:
#1차원에 2차원 배열을 더해보자
M = np.ones((3,2))
a = np.arange(3)[:,np.newaxis]

In [57]:
M+a

array([[ 1.,  1.],
       [ 2.,  2.],
       [ 3.,  3.]])

M의 배열이 2,3이고 a의 배열이 (3,) 인 경우


## 실전 브로드캐스팅
진작에 이거부터 할걸그랬다.
ufunc을 사용하면 느린 파이썬 루프를 명시적으로 안써도 된다.

## 데이터 중앙정렬하기?

In [71]:
X = np.random.random((10,3)) #10x3의 배열을 만들었다.
Xmean = X.mean(0) #0은 col 기준, 1은 row기준
Xmean

array([ 0.37234258,  0.58285884,  0.48128706])

In [78]:
#평균값을 뺌으로써 X배열을 중앙정렬할 수 있다.
X_centered = X - Xmean
X_centered.mean(0)

array([  2.22044605e-17,   4.44089210e-17,   4.99600361e-17])

## 2차원 함수를 플롯-팅 해보자
브로드캐스팅은 2차원 함수를 기반으로 이미지를 그릴때도 유용하다고 한다!
함수를 정의하고 싶다면 브로드캐스팅을 사용해 그리드에 이 함수를 계산할 수 있다. 이게 무슨소리야

In [97]:
#x와 y는 0에서 5까지 50단계로 나눈 배열이다.
x = np.linspace(0,5,50)
y = np.linspace(0,5,50)[:,np.newaxis]
z = np.sin(x) ** 10 + np.cos(10 + y*x) * np.cos(x)

In [98]:
#2차원 배열을 플롯팅하는데 matplotlib을 사용한다. 
%matplotlib inline
import matplotlib.pyplot as plt

In [99]:
plt.imshow(z, origin='lower',extent = [0, 5, 0, 5], cmap = 'viridis')
plt.colorbar();
#난 도대체 뭘 그린걸까 2차원의 함수를 색상으로 나타낼 수 있다.
#옆에 있는 것을 밀도플롯과 등고선 플롯을 그릴 수 있다. 